### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [mscates/first-journey#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by mscates** [comment]
I found this and put it in the application.html.erb file.  <meta name="viewport" content="width=device-width, initial-scale=1.0">   It does look better on mobile.  thank you

**Comment by kenmazaika** [comment]
Awesome!  The code in the template looks perfect! :+1:
